---
title: "Data Manipulation"
output: github_document
---

```{r setup}
library(tidyverse)
```
## Load in the FAS litters Data

```{r}
litters_df <- read_csv("./data/FAS_litters.csv")
litters_df <- janitor::clean_names(litters_df)
```

## Select

Choose some of the columns and not others

```{r}
select(litters_df,group,gd0_weight)
```

```{r}
select(litters_df,group,gd0_weight:gd_of_birth)
```

```{r}
select(litters_df,-litter_number)
```

select and rename columns:

```{r}
select(litters_df,GROUP = group, LITTER_NUMBER = litter_number)
```

Select helpers

```{r}
select(litters_df,starts_with("gd"))
```

Make tibble start with a specific column

```{r}
select(litters_df,litter_number,everything())
```

Same as above

```{r}
relocate(litters_df,litter_number)
```

## Rename

Rename columns withoutselecting them

```{r}
rename(litters_df,GROUP = group, LITTER_NumBer = litter_number)
```

## Filter

Filter is intended to remove or keep rows. TRUE -> keep, FALSE -> remove

```{r}
filter(litters_df, gd0_weight <22)
```

```{r}
filter(litters_df,gd0_weight >= 22)
```

```{r}
filter(litters_df,gd_of_birth == 20)
```

```{r}
filter(litters_df,gd_of_birth != 20)
```

```{r}
filter(litters_df,gd0_weight >= 22,gd_of_birth == 20)
```

```{r}
filter(litters_df,group == "Con7")
```

```{r}
filter(litters_df,group %in% c("Con7","Mod8"))
```

