---
title: "Tidy Data"
output: github_document
---

```{r setup}
library(tidyverse)
```

## povit_longer

Load the PULSE data,

```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
```

Wide format to long format

```{r}
pulse_data_tidy = 
  pulse_data %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  )
```

Rewrite, combine and extend(to add a mutate)

```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  ) %>% 
  relocate(id,visit) %>% 
  mutate(visit = recode(visit,"bl" = "oom"))
```


## pivot_wider

Make up some data

```{r}
analysis_result = tibble(
  group = c("treatment","treatment","placebo","placebo"),
  time = c("pre","post","pre","post"),
  mean = c(4,8,3.5,4)
)

analysis_result %>% 
  pivot_wider(
    names_from = 'time',
    values_from = "mean"
  )
```


## Binding rows

Using the LotR data

First step: import each table.

```{r}
fellowship_ring = readxl::read_excel("./data/LotR_Words.xlsx",range = "B3:d6") %>% 
  mutate(movie = "fellowship_ring")

two_towers = readxl::read_excel("./data/LotR_Words.xlsx",range = "F3:H6") %>% 
  mutate(movie = "two_towers")

return_king = readxl::read_excel("./data/LotR_Words.xlsx",range = "j3:l6") %>% 
  mutate(movie = "return_king")
```

Bind all the row together

```{r}
lotr_tidy = bind_rows(fellowship_ring,two_towers,return_king) %>% 
  janitor::clean_names() %>% 
  relocate(movie) %>% 
  pivot_longer(
    female:male,
    names_to = "gender",
    values_to = "words")
```

## joining datasets

Import and clean the FAS datasets

```{r}
pups_df = 
  read_csv("./data/FAS_pups.csv") %>% 
  janitor::clean_names() %>% 
  mutate(sex = recode(sex,`1` = "male",`2` = "female"))

litters_df = 
  read_csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  relocate("litter_number") %>% 
  separate(group, into = c("does","day_of_tx"),sep = 3)


```

Join them

```{r}
fas_df =
  left_join(pups_df,litters_df,by = "litter_number") %>% 
  arrange(litter_number) %>% 
  relocate(litter_number,sex,does,day_of_tx)
```

